### ISSUE TITLE
`cp` fails with `--no-clobber`, causing installation to end early

### ISSUE THREAD

**Issue by ethanalker** [Furglitch/modorganizer2-linux-installer#492]
Related to #480 

Using GNU coreutils `cp`:

```bash
$ cp --version
cp (GNU coreutils) 9.3
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.
```
In `bash`:

```bash
$ touch foo
$ touch bar
$ cp --no-clobber foo bar || echo 'baz'
cp: not replacing 'bar'
baz
```

`cp` fails, causing the script to end early

Perhaps the issue is with a different version of `cp`? I can't provide full script install logs ATM but I can update the issue with them later. I'm on Arch Linux and I'm using the coreutils provided by Arch.

**Comment by rockerbacon** [comment]
Related to [https://bugs.gnu.org/62572](https://bugs.gnu.org/62572).
`cp` behaviour for the `--no-clobber` option changed in coreutils 9.2 and a new option `--update=none` was added in 9.3 so that it would be possible to recreate the 9.1 behaviour.
For now this should only affect bleeding edge distros as coreutils 9.2 is still relatively new.

The idea behind `--no-clobber` was to avoid replacing script extenders during an update, since it has the potential to break a modlist. The optimal solution would be to actually check whether the script extender is already installed before even downloading it.

A good compromise would be to unset the `e` option before the copy, which would allow bash to continue execution.

**Comment by ethanalker** [comment]
It can also be solved by appending `|| true` to the `cp` command instead of unsetting `e`. 

The issue with both of these approaches is that if the `cp` fails for other reasons (e.g. permissions) we won't know, which is why I sent a warning in my original PR. The optimal solution as you mentioned would be to check manually before the `cp`, since I don't see a clean way to support both pre-9.2 and post-9.3 versions of `cp`.
