### ISSUE TITLE
recommendation to delete prefix during installation should be removed, or recovery option created

### ISSUE THREAD

**Issue by cat40** [Furglitch/modorganizer2-linux-installer#539]
When running the install script, including running it to *update*, rather than install, the program, the following message appears:

> It is highly recommended to clean your current game prefix
>before starting the installation process.
>
>Would you like to delete your current game prefix and
>create a new one?

Given that if the user selects yes, `rm -rf $game_compatdata` is the result, which I will point out is rather permanent  and destructive if done incorrectly, I think the recommendation should be removed, or at least the strength of it. It is not a good idea to delete the prefix when updating, especially if not using a portable instance, because it will delete the current instance entirely, including all installed mods. 

Alternatively, change the `rm` to an `mv` and just move the files to a backup, tell the user where it is, and allow them to decide when to delete it after verifying everything works. 

When doing a new install, removing the prefix may or may not be a good idea, and when upgrading, removing it is *entirely incorrect* and will result in loss of important data. Given that, I suggest that the recommendation is at present incorrect and should be removed, if not replaced with a warning.

**Comment by ronlaws86** [comment]
I'd like to add to this in order to streamline the process. 
The recommendation to delete the prefix is 'Highly recommended' but after doing so it does not instruct you to re-run the game in steam to create a new one. 

this step should be altered to either say that if this is the first time running this installer for this game or you have only just installed the game then you can skip this step. 
After if you choose to delete the prefix (for which there are valid reasons to do so) then it should as the next step ask you to re-runt he game in steam to generate a new prefix. Otherwise the installer will fail and you will ahve to re-run the installer from scratch again after creating a new prefix which it only asks you to do after failing. 

alternatively, at the phase where it needs to make changes to the prefix, it should check if it exists first and if not ask you to create it before continuing, **instead of trying and failing the whole installer.**

**Comment by rockerbacon** [comment]
> I'd like to add to this in order to streamline the process.
The recommendation to delete the prefix is 'Highly recommended' but after doing so it does not instruct you to re-run the game in steam to create a new one.
>
> this step should be altered to either say that if this is the first time running this installer for this game or you have only just installed the game then you can skip this step.
After if you choose to delete the prefix (for which there are valid reasons to do so) then it should as the next step ask you to re-run the game in steam to generate a new prefix. Otherwise the installer will fail and you will have to re-run the installer from scratch again after creating a new prefix which it only asks you to do after failing.
>
> alternatively, at the phase where it needs to make changes to the prefix, it should check if it exists first and if not ask you to create it before continuing, instead of trying and failing the whole installer.

This is unrelated to the original issue. There already exists a prompt with instructions to execute the game again right after removal of the existing prefix, and a check is also executed to ensure the prefix directory exists before proceeding with the install process. Please refer to [step/clean_game_prefix.sh](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/step/clean_game_prefix.sh) for any clarifications.

**Comment by rockerbacon** [comment]
I agree that adjusting the process is a good idea.

First I'd like to clarify that removal of the prefix is always recommended regardless of whether it is a first time install or an upgrade. The process is there to improve overall stability by suggesting users place their prefixes at a known, tested state before any changes are applied to them. Due to resource constraints of this project, only a single state is tested and that is installation upon a newly created prefix using the recommended Proton version. Note that different installer versions may require a different set of Protontricks, Proton versions and workarounds and without a complete purge of the prefix, it would be necessary to implement a fairly complex upgrade process.
The decision was made after confirmation that Steam does not modify the prefix when changing Proton versions and that this causes erratic behaviour after specific version changes.

The process I'd recommend is:
1. Move the compatdata directory from `$game_compatdata` to `${game_compatdata}.${timestamp}` to avoid any destructive operations
2. Instruct users to create a new prefix (current behaviour)
3. Copy the contents of `${game_compatdata}.${timestamp}/pfx/drive_c/users` to the newly created `${game_compatdata}/pfx/drive_c/users` to reduce the need for manual data restoration after the cleaning process

**Comment by rockerbacon** [comment]
I do not have the time to implement any changes right now. Pull requests are welcome.
