### ISSUE TITLE
Issues with MO2 not detecting plugins when launched through Skyrim

### ISSUE THREAD

**Issue by spacecowboyx** [Furglitch/modorganizer2-linux-installer#546]
Using Proton GE 8-06 as the forced compatibility on the steam deck but when launched from Skyrim it does not detect any plugins as in they are there in the window but any application launched from MO2 does not load the plugins. 

This also means skse64 does not load any plugins either. For whatever reason, if I add MO2 as a non steam game then everything works, all the executibles work and load the active plugin list. The only thing that doesn't is launching skse which launches Skyrim which launches Mo2 again then the game.

Launching through Skyrim seems like it is only loading in the prefix or something else and not within the Mo2 folder so it launches the game vanilla. I have reinstalled several times and wiped the prefix and the issue persists. Have also wiped the game folder.

**Comment by rockerbacon** [comment]
The issues you're experiencing suggest USVFS is not working. Have you tried using standard Proton 8 instead of Proton GE?

**Comment by spacecowboyx** [comment]
I have not but tried 6 all the way to 8-26. Since I wrote this I kinda fixed the main Skyrim MO2 exe so it'll launch the game with mods. However, xedit and now LOOT are the only external programs that work. Bodyslide, Nemesis, and others like them that require the data folder do not launch with usvfs spoofed data folder so they don't see the plugins or data within mods.

However, again if I use the added mo2 directly from steam I can run bodyslide and nemesis and they will pick up the data. Both the external mo2 instance and the Skyrim one are using the same proton. Technically they both launch the same instance because it's the same folder but somehow it seems like the usvfs is having issues making the connection within the prefix.  

It's really weird man. Idk if it's Skyrim or steam or protontricks but something is wrong. I did try a clean install but that did not fix it, at least not entirely. I can also run Skyrim MO2 and the steam mo2 in tandem which is what I've been doing since the Skyrim update until we can fix it. The only time it ever worked completely was the very first time I installed it back in November.

**Comment by rockerbacon** [comment]
I ran into this issue today while moving the game between libraries. What I can confirm so far is that symbolic links don’t work properly with USVFS.

In my case, I had to change some paths in MO2 to point to the new Steam library location. For some paths I used “$HOME/.steam/steam” and for others “$HOME/.local/share/Steam”. Despite the former being a symlink to the later, USVFS broke completely and it was not possible to access virtual files through the symlink.

Could you check whether the applications that are broken for you are using symlinks in any capacity?

**Comment by suamor** [comment]
I have a similar situation, where the mods are on an external drive.
When I install ModOrganizer, everything is in the prefix.

Then I copy over the old settings from external drive.
Now parts of the installation (that is from MO2, not from installer) are in "steamuser" AppData/Local.
Other parts are in the local MO2/Modding folder.

I read instructions for MO2 setup on Linux where they recommend to create empty folders for OutfitStudio ("CalienteTools/BodySlide") and Nemesis ("Nemesis_Engine") in the Game folder (for me inside a SteamLibrary). I'm not sure why these mods require this extra step on Linux. Maybe USVFS has problems with external drives.

Now you can either copy / move all files from your external installation (then you have to change the path settings) or link the paths that are not working. In your case checking and optionally linking the "mods" folder should be enough.

Current LOOT will not work with any proton GE version since they have not integrated the Qt6 Patch (and the project also does not use github issues, so you can't report it properly or check if they are aware of the issue). 

Proton TKG has the patch integrated but the builds do not work with Ubuntu LTS or similar distributions using older libc.

**Comment by rockerbacon** [comment]
Install location issues are now grouped in #656
