### ISSUE TITLE
Update F4SE

### ISSUE THREAD

**Issue by rockerbacon** [Furglitch/modorganizer2-linux-installer#628]
The installer currently installs an outdated F4SE version. Need to update it to the latest version

**Comment by StellarHarbour** [comment]
So each time utility mod updated installer requires update too?

**Comment by swjzielinski** [comment]
The latest F4SE version is 0.6.23 and that is what the script installs. It was changed in the script in January 2023.

@StellarHarbour yes, unfortunately. Although it might be possible to pull the latest version from files on github. 
For example we can use 
`curl -sL https://api.github.com/repos/AUTHOR/REPO/releases/latest | jq -r ".tag_name"`
to find the latest release version. 
@rockerbacon Perhaps this could be implemented somehow, so that the install script would automatically download the latest version of certain files? For example skse64 and f4se can be downloaded from github, not to mention the JDK, MO2 and winetricks.

**Comment by StellarHarbour** [comment]
> The latest F4SE version is 0.6.23 and that is what the script installs. It was changed in the script in January 2023.
> 
> @StellarHarbour yes, unfortunately. Although it might be possible to pull the latest version from files on github. For example we can use `curl -sL https://api.github.com/repos/AUTHOR/REPO/releases/latest | jq -r ".tag_name"` to find the latest release version. @rockerbacon Perhaps this could be implemented somehow, so that the install script would automatically download the latest version of certain files? For example skse64 and f4se can be downloaded from github, not to mention the JDK, MO2 and winetricks.

Latest version is 0.7.1, https://www.nexusmods.com/fallout4/mods/42147?tab=files
And when you propose QOL improvements here issues is always closed next minute

**Comment by swjzielinski** [comment]
> Latest version is 0.7.1
That is the highly experimental version for the new update. It hasn't been released on the official website or the github yet.

**Comment by StellarHarbour** [comment]
It doesn't work like that, it latest version for Steam and you can't use another, that's why there should be option to provide manual link for your downloads

**Comment by swjzielinski** [comment]
You can downgrade to the previous version quite easily, I did it myself. If you don't clean the whole folder, just paste in the old files and delete the files starting with 'cc' from the Data folder, the game will work and Steam won't even know you downgraded the game since the file in the game directory that tells Steam what the version is wasn't changed.

**Comment by swjzielinski** [comment]
If someone really wants to play on the newest version with the newest F4SE, they can download the files and extract them into the game folder.

**Comment by StellarHarbour** [comment]
I don't even know why it installs F4SE by itself, it have nothing to do with mod organizer 2

**Comment by swjzielinski** [comment]
It's … kind of needed for 90%+ of mods, also some people don't know where to put it.

One more thing, right now the new F4SE is only accessible on Nexus, where you need to have an account to download. So the script can't download it. Which is why it will remain with the older version for now.

**Comment by StellarHarbour** [comment]
Don't you need Nexus account to download mods too? KEKW

**Comment by swjzielinski** [comment]
> Don't you need Nexus account to download mods too? 

Sure, but you download them yourself. If the script was to download F4SE from Nexus, it would have to know your login and password, which is a potential security breach.

>Basically as I said, there's no reason to provide outdated utility mods with installer

The script uses the latest stable release. Almost all programs will do it the same way, sticking to the latest stable release even if the next version has some amazing new features. Stability is important, you know.

**Comment by StellarHarbour** [comment]
Whatever, anyway none of QOL never pass here and I use it to only get working MO2 with NXM
